### ISSUE TITLE
Documentation: Add user examples

### ISSUE THREAD

**Issue by frankpopham** [martinctc/parallaxr#4]
Hi,

Came across your excellent package and thought that it could be used to improve readability of academic papers as set out in this small example - https://frankpopham.github.io/side/  . so just to say many thanks

**Comment by martinctc** [comment]
@frankpopham , this is awesome! Thank you so much! Are you happy for me to place this as an example on the README?

**Comment by ries9112** [comment]
When following the example and constructing the object `md_tibble` I was getting the error `Error in .f(.x[[i]], ...) : unable to find yaml delimiters` because I did not have a folder dedicated to the .md files.

I looked at the example created by @frankpopham and the addition of `pattern=".md"` when calling `list.files()` to construct `all_md_str` fixed the problem, see the results before and after adding in the additional `pattern` parameter:
![image](https://user-images.githubusercontent.com/32306488/101570411-96541280-3993-11eb-8d59-ed245845422b.png)

Personally I think this is a nice addition to the example provided! Changing this line:
```
## Character vector of all MD files
all_md_str <- list.files(path = "documents/parallax", pattern=".md", full.names = TRUE)
```
where the `pattern` parameter is also passed.

I am happy to make the change and make a pull request but figured I would just leave a comment here instead.

Thanks to @frankpopham for the example and to @martinctc for a seriously awesome R Markdown output type!!

**Comment by durraniu** [comment]
I want to thank all of you for the package and great examples. Here's my attempt: https://durraniu.github.io/BBC100/  
Code: https://github.com/durraniu/BBC100

**Comment by martinctc** [comment]
@durraniu and @frankpopham - thank you both - will add your examples to the documentation of this package (unless you object, in which case please tell me!) 😄

**Comment by martinctc** [comment]
Examples have been added to #8  in the README page, as well as instructions for new contributors to add entries.
